#
# Assemble Pro
#
{
	'name': 'Assemble Pro',
	'version': '1.0',
	'author': 'MSP1 Managed IT Services Pvt Ltd.',
	'sequence': 1,
	'category': 'Assembling Lift',
	'description': """
# Lift Assembling module
""",
	'depends': [
		'web',
		'sale',
		'sale_stock',
		'purchase',
		'payment',
		'odoo_material_old_layout',
		'rowno_in_tree',
		'account_voucher',
		'account_accountant',
		'stock_split_availability',
		'decimal_precision',
		'stock_account',
		'stock_barcode',
		'web_menu_hide_9',
		'web_tree_image',
		'menu_collapsible',
		'stock_transfer_restrict_lot',
		'hr',
		'hr_payroll',
		'hr_contract',
		'hr_attendance',
		'document',
		'barcodes',
		'mrp',
		'delivery',
		'l10n_in',
		'l10n_in_hr_payroll',
	],
	'data': [
		'security/assemble_pro_security.xml',
		'security/ir.model.access.csv',
		'sequence/assemble_pro_sequence.xml',
		'data/res.country.csv',
		'data/res.country.state.csv',
		'data/res.partner.csv',
		'data/res.company.csv',
		'data/product.template.csv',
		'data/stock.picking.type.csv',
		'data/assemble_pro_data.xml',
		'wizard/sale_make_invoice_advance_extension.xml',
		'wizard/mrp_product_produce_view_extension.xml',
		'views/res_company_extension_view.xml',
		'views/product_extension_view.xml',
		'views/delivery_challan_report_view.xml',
		'views/mrp_extension_view.xml',
		'views/sale_order_extension_view.xml',
		'views/account_extension_view.xml',
		'views/claim_management_view.xml',
		'views/purchase_extension_view.xml',
		'views/work_order_view.xml',
		'views/res_partner_extension_view.xml',
		'views/res_users_extension_view.xml',
		'views/packaging_extension_view.xml',
		'views/res_country_extension_view.xml',
		'views/supplier_pricelist_extension_view.xml',
		'views/assemble_instruction_view.xml',
		'views/assemble_pro.xml',
		'views/stock_extension_view.xml',
		'views/hr_extension_view.xml',
		'views/advance_material_plan_view.xml',
		'views/tally_export_view.xml',
		'views/sales_declaration_view.xml',
		'views/handeling_unit_barcode_view.xml',
		'views/stock_dashboard_extension.xml',
		# 'views/assemble_pro_template.xml',
		'views/otd_calculation_view.xml',
		'report/sales_declaration_report.xml',
		'report/handeling_unit_barcode_report.xml',
		'report/invoice_report.xml',
		'report/report_challan.xml',
		'report/report_stockpicking_operations_exception.xml',
		# 'report/report_shipping_delivery.xml',
		'report/purchase_report.xml',
		'report/product_barcode_report.xml',
		'report/header_footer_layout.xml',
		'views/legal_compliance_view.xml',
		'views/legal_compliance_template.xml',
		'views/legal_compliance_cron.xml',
		'views/modvat_template.xml',
		'views/modvat_cron.xml',
		'views/sale_reports_view.xml',
		'views/sale_register_reports_view.xml',
		'views/rg_export_reports_view.xml',
		'views/purchase_reports_view.xml',
		'views/packing_list_reports_view.xml',
		'views/fg_summary_reports_view.xml',
		'views/pcb_details_reports_view.xml',
		'views/rm_serial_search_reports_view.xml',
		'views/rm_stock_summary_reports_view.xml',
		'views/msl_reports_view.xml',
		'views/issue_note_register_reports_view.xml',
		'views/assemble_pro_menus.xml',
	],
	'qweb' : [
		"static/src/xml/base_extension.xml",
	],
	'installable' : True,
	'application' : True,
}